services:
  pgadmin:
    image: dpage/pgadmin4:8
    profiles: ["tools"]
    ports: ["5050:80"]
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Dockerfile
    # keep ONLY ONE command (with debugpy)
    command: sh -c "python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./app:/app/app:rw
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  seed:
    build: .
    profiles: ["tools"]
    command: python -c "import app.seed"
    depends_on:
      db:
        condition: service_healthy

  test:
    build: .
    profiles: ["tools"]
    command: sh -c "pip install -q pytest && pytest -q"
    volumes:
      - ./app:/app/app:rw
      - ./tests:/app/tests:rw
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
